# Sourced by ../build.sh; build Bottles from upstream GitHub into lolios-local

# 6B. Bottles from GitHub
# ------------------------------------------------------------

build_lolios_bottles_github_pkg() {
    local pkgname="bottles"
    local ref="${BOTTLES_GIT_REF:-main}"
    local pkgroot="$WORKROOT/bottles-github-pkg"
    local srcdir="$pkgroot/src"
    local srcrepo="$srcdir/Bottles"
    local logf="$LOG_DIR/bottles-github-$BUILD_ID.log"

    if [ "$FORCE_REPO_REBUILD" != "1" ] && local_repo_has_pkg "$pkgname"; then
        log "Bottles already exists in local repo; skipping GitHub build"
        return 0
    fi

    log "Building Bottles from GitHub into local repo: bottlesdevs/Bottles@$ref"
    mkdir -p "$CUSTOMREPO" "$REPO_DIR" "$LOG_DIR" "$srcdir"
    rm -rf "$pkgroot"
    mkdir -p "$srcdir"
    : >"$logf"

    if ! git clone --depth=1 --branch "$ref" "https://github.com/bottlesdevs/Bottles.git" "$srcrepo" >>"$logf" 2>&1; then
        warn "Nie udało się pobrać Bottles z GitHub. Log: $logf"
        warn "Bottles pozostanie opcjonalne i zostanie usunięte z listy ISO, jeśli nie ma artefaktu w repo."
        return 0
    fi

    cat > "$pkgroot/PKGBUILD" <<'PKGEOF'
pkgname=bottles
_pkgname=Bottles
pkgver=63.2.lolios
pkgrel=5
pkgdesc='Easily manage Wine and Proton prefixes - LoliOS GitHub build'
arch=('any')
url='https://github.com/bottlesdevs/Bottles'
license=('GPL-3.0-only')
provides=('bottles')
conflicts=('bottles')
depends=(
  'python'
  'python-gobject'
  'python-cairo'
  'python-orjson'
  'gtk4'
  'gtksourceview5'
  'libadwaita'
  'libportal-gtk4'
  'glib2'
  'gdk-pixbuf2'
  'pango'
  'hicolor-icon-theme'
  'dconf'
  'cabextract'
  'p7zip'
  'imagemagick'
  'wine'
  'xorg-xdpyinfo'
)
optdepends=(
  'gamemode: game performance integration'
  'gvfs: file manager integration'
  'vkd3d: Direct3D 12 translation layer'
  'lib32-vkd3d: 32-bit Direct3D 12 translation layer'
  'vulkan-icd-loader: Vulkan support'
  'lib32-vulkan-icd-loader: 32-bit Vulkan support'
)
makedepends=(
  'git'
  'meson'
  'ninja'
  'blueprint-compiler'
  'python-pip'
  'python-build'
  'python-installer'
  'python-wheel'
  'desktop-file-utils'
  'appstream-glib'
)
source=()
sha256sums=()

prepare() {
  cd "$srcdir/$_pkgname"
  rm -rf build vendor requirements.lolios.txt

  sed -i 's/if not fs.is_file.*$/if false/' bottles/frontend/meson.build
  sed -i '/if not Xdp.Portal.running_under_sandbox()/,/^            return$/s/^/#/' bottles/frontend/window.py 2>/dev/null || true

  # Vendor only Python dependencies that are safe to bundle.
  # Do not vendor/build orjson from Bottles requirements: pinned orjson 3.10.7
  # uses PyO3 that supports Python <=3.13, while current Arch may ship Python 3.14.
  # Arch python-orjson is used instead via depends=().
  grep -Ev '^(PyGObject|pycairo|wheel)==|^#|^[[:space:]]*$' requirements.txt > requirements.lolios.txt
  sed -i -E '/^[[:space:]]*orjson([<=>!~ ].*)?$/Id' requirements.lolios.txt
  if grep -qi '^[[:space:]]*orjson' requirements.lolios.txt; then
    echo "orjson must not be vendored for LoliOS Bottles build" >&2
    cat requirements.lolios.txt >&2
    return 1
  fi
}

build() {
  cd "$srcdir/$_pkgname"
  python -m pip install --no-cache-dir --no-warn-script-location --target "$srcdir/vendor" -r requirements.lolios.txt
  meson setup build --prefix=/usr --buildtype=plain -Dprofile=default
  ninja -C build
}

package() {
  cd "$srcdir/$_pkgname"
  DESTDIR="$pkgdir" ninja -C build install

  install -d "$pkgdir/usr/share/bottles/vendor"
  cp -a "$srcdir/vendor"/. "$pkgdir/usr/share/bottles/vendor/"

  if [ -f "$pkgdir/usr/bin/bottles" ]; then
    sed -i '/import sys/a sys.path.insert(0, "/usr/share/bottles/vendor")' "$pkgdir/usr/bin/bottles"
  fi

  local license_file=""
  for candidate in LICENSE LICENSE.md LICENSE.txt COPYING COPYING.md COPYING.txt; do
    if [ -f "$candidate" ]; then
      license_file="$candidate"
      break
    fi
  done
  if [ -n "$license_file" ]; then
    install -Dm644 "$license_file" "$pkgdir/usr/share/licenses/$pkgname/$(basename "$license_file")"
  else
    install -Dm644 /dev/stdin "$pkgdir/usr/share/licenses/$pkgname/LICENSE.lolios" <<'EOF_LICENSE'
Bottles is distributed under the GPL-3.0-only license according to the LoliOS
package metadata. Upstream source: https://github.com/bottlesdevs/Bottles
EOF_LICENSE
  fi

  [ -f README.md ] && install -Dm644 README.md "$pkgdir/usr/share/doc/$pkgname/README.md" || true
  install -Dm644 /dev/stdin "$pkgdir/usr/share/doc/$pkgname/README.lolios" <<'EOF'
This Bottles package is generated by the LoliOS builder directly from
https://github.com/bottlesdevs/Bottles and embedded in the lolios-local repository.
The installed system can therefore install Bottles offline from /opt/lolios/repo.
Python-only dependencies such as patool and icoextract are vendored under
/usr/share/bottles/vendor. orjson is intentionally provided by Arch python-orjson
because Bottles' pinned orjson may lag behind the current Arch Python ABI.
EOF
}
PKGEOF

    if ! (cd "$pkgroot" && makepkg -s --noconfirm --needed --force >"$logf" 2>&1); then
        warn "Budowa Bottles z GitHub nie powiodła się. Log: $logf"
        warn "Jeśli Bottles ma być obowiązkowy, napraw zależności z logu i uruchom ponownie."
        return 0
    fi

    shopt -s nullglob
    local built=( "$pkgroot"/*.pkg.tar.zst )
    shopt -u nullglob
    if [ "${#built[@]}" -gt 0 ]; then
        cp -f "${built[@]}" "$CUSTOMREPO/"
        cp -f "${built[@]}" "$REPO_DIR/"
        log "Bottles GitHub package added to local repo"
    else
        warn "Brak artefaktu bottles po makepkg. Log: $logf"
    fi
}

build_lolios_bottles_github_pkg
refresh_local_repo
copy_customrepo_to_repo_dir
sync_embedded_local_repo

# ------------------------------------------------------------
