# Sourced by ../build.sh; original section: 19. Boot menu names, UEFI install entry, Safe Graphics / Recovery

# 19. Boot menu names, UEFI install entry, Safe Graphics / Recovery
# ------------------------------------------------------------

log "Writing ArchISO-compliant UEFI boot entries"

ENTRY_DIR="$PROFILE/efiboot/loader/entries"
LOADER_CONF="$PROFILE/efiboot/loader/loader.conf"
if [ -d "$ENTRY_DIR" ]; then
    mkdir -p "$ENTRY_DIR" "$(dirname "$LOADER_CONF")"

    # Clean only entries generated by older broken LoliOS boot patches.
    # Keep upstream archiso entries unless we intentionally overwrite the main one below.
    rm -f \
        "$ENTRY_DIR/00-lolios-install.conf" \
        "$ENTRY_DIR/01-lolios-safe-graphics.conf" \
        "$ENTRY_DIR/02-lolios-recovery.conf" \
        "$ENTRY_DIR/02-lolios-safe-graphics.conf" \
        "$ENTRY_DIR/03-lolios-recovery.conf"

    # Do NOT use %INSTALL_DIR% / %ARCHISO_LABEL% here. On the broken images these
    # placeholders were not expanded before systemd-boot checked the entry.
    # This profile installs linux-zen and linux-lts into the live ISO, and mkarchiso
    # generated these real payload names under work/iso/arch/boot/x86_64:
    #   vmlinuz-linux-zen / initramfs-linux-zen.img
    #   vmlinuz-linux-lts / initramfs-linux-lts.img
    # Therefore UEFI entries must point to linux-zen for the primary installer
    # and linux-lts as fallback.
    ISO_BOOT_LABEL="${ISO_BOOT_LABEL:-${ISO_LABEL_PREFIX:-LOLIOS}_$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y%m)}"
    ISO_BASEDIR="${ISO_BASEDIR:-arch}"
    ISO_KERNEL_ZEN="/${ISO_BASEDIR}/boot/x86_64/vmlinuz-linux-zen"
    ISO_INITRD_ZEN="/${ISO_BASEDIR}/boot/x86_64/initramfs-linux-zen.img"
    ISO_KERNEL_LTS="/${ISO_BASEDIR}/boot/x86_64/vmlinuz-linux-lts"
    ISO_INITRD_LTS="/${ISO_BASEDIR}/boot/x86_64/initramfs-linux-lts.img"

    write_uefi_entry() {
        local file="$1" title="$2" kernel="$3" initrd="$4" extra_options="${5:-}"
        cat > "$file" <<EOFBOOT
sort-key 01
location filesystem
architecture x64
title   $title
linux   $kernel
initrd  $initrd
options archisobasedir=$ISO_BASEDIR archisolabel=$ISO_BOOT_LABEL $extra_options
EOFBOOT
    }

    # Overwrite/create the canonical archiso Linux entry name as the main installer.
    # Keep a separate LTS fallback entry for machines that fail with zen.
    write_uefi_entry "$ENTRY_DIR/01-archiso-x86_64-linux.conf" "LoliOS Install Medium (linux-zen)" "$ISO_KERNEL_ZEN" "$ISO_INITRD_ZEN" ""
    write_uefi_entry "$ENTRY_DIR/02-lolios-safe-graphics.conf" "LoliOS Install Medium (linux-zen, Safe Graphics)" "$ISO_KERNEL_ZEN" "$ISO_INITRD_ZEN" "nomodeset"
    write_uefi_entry "$ENTRY_DIR/03-lolios-lts.conf" "LoliOS Install Medium (linux-lts fallback)" "$ISO_KERNEL_LTS" "$ISO_INITRD_LTS" ""
    write_uefi_entry "$ENTRY_DIR/04-lolios-lts-safe-graphics.conf" "LoliOS Install Medium (linux-lts, Safe Graphics)" "$ISO_KERNEL_LTS" "$ISO_INITRD_LTS" "nomodeset"
    write_uefi_entry "$ENTRY_DIR/05-lolios-recovery.conf" "LoliOS Recovery Shell (linux-zen)" "$ISO_KERNEL_ZEN" "$ISO_INITRD_ZEN" "systemd.unit=multi-user.target nomodeset"

    # Keep Memtest/EFI Shell entries, but default to the real installer entry.
    cat > "$LOADER_CONF" <<'EOFBOOT'
default 01-archiso-x86_64-linux.conf
timeout 10
console-mode max
editor no
EOFBOOT
fi

log "Patching boot menu names only; preserving ArchISO live kernel/initramfs paths"

# Patch branding only. Never rewrite vmlinuz/initramfs to linux-zen inside ISO boot entries.
find "$PROFILE/efiboot" "$PROFILE/grub" "$PROFILE/syslinux" -type f 2>/dev/null -exec sed -i \
    -e 's/Arch Linux install medium/LoliOS install medium/g' \
    -e 's/Arch Linux archiso x86_64/LoliOS x86_64/g' \
    -e 's/Arch Linux/LoliOS/g' \
    {} + || true

# ------------------------------------------------------------
